server:
  port: 8082

spring:
  application:
    name: ms-inventory
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5433/db_inventory
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
  docker:
    compose:
      file: cordillera/data-sources/ms-inventory/docker-compose.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true