version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: postgres-ms-reporting
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_reporting
    ports:
      - "5436:5432"
    restart: unless-stopped
