version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: postgres-ms-kpis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_kpis
    ports:
      - "5435:5432"
    restart: unless-stopped
